import gradio as gr
from together import Together
import re

import os
print(os.getenv('MODEL_REPO_ID'))

client = Together(api_key=os.getenv('TOGETHER_API_KEY'))

memory = []

SINGLE_GENERATOR_PROMPT = """
You're an experienced researcher named Nimible. Your goal is to perform a deep research & provide a succinct answer to <user input>. 
Always mention citations or sources of information you used to generate your answer.
Your response should be in markdown format, with proper headings and structure. Avoid LaTeX or other complex formatting.
"""

GENERATOR_PROMPT = """
You're an experienced researcher. Your goal is to perform a deep research & provide an answer to <user input>. 
Always mention citations or sources of information you used to generate your answer.
If there are action_items suggested with 'DR_FAIL', incorporate them to improve your solution & reprint your complete answer, without pointing out the edits made.
Your response should be in markdown format, with proper headings and structure. Avoid LaTeX or complex formatting.
"""

EVALUATOR_PROMPT = """
You are an experienced evaluator. Your task is to assess the quality of the generated content based on the original task.
You will receive a task and the content generated by the researcher.
Evaluate the content based on the following criteria:
1. Completeness: Does the content fully address the task?
2. Accuracy: Is the information provided correct and reliable?
3. Clarity: Is the content well-structured and easy to understand?
4. Relevance: Is the content relevant to the task?
5. Citations: Are sources of information properly cited?

If the content meets all criteria, return "DR_PASS". 
If it neeeds improvement or fails to meet the criteria, return "DR_FAIL" with comprehensive action items to remediate the concerns.

Your response should be in JSON format with the following schema:
{
    "evaluation": "DR_PASS" | "DR_FAIL",
    "action_items": "Your action items here"
}
"""

def generate(query: str, generator_prompt: str, context=None) -> tuple[str, str]:
    """Generate and improve a solution based on feedback."""

    if context:
        query = f"{context}\n{query}"

    response = run_llm(user_prompt=query, model="lgai/exaone-3-5-32b-instruct", system_prompt=generator_prompt)
    
    return response

def evaluate(task : str, evaluator_prompt : str, generated_content: str) -> tuple[str, str]:
    """Evaluate if a solution meets requirements."""
    full_prompt = f"Original task: {task}\nContent to evaluate: {generated_content}"

    response = JSON_llm(full_prompt, evaluator_prompt)

    return response

def loop_workflow(task: str, evaluator_prompt: str, generator_prompt: str) -> tuple[str, list[dict]]:
    """Keep generating and evaluating until the evaluator passes the last generated response."""
    # Store previous responses from generator

    # Generate initial response
    response = generate(task, generator_prompt)

    memory.append(response)

    result = evaluate(task, evaluator_prompt, response)
    # Terminating condition
    if "DR_PASS" in result:
        return ""
    
    # Add current response and feedback to context and generate a new response
    context = "\n".join([
        *[f"- {m}" for m in memory]
    ])

    response = generate(result, generator_prompt, context)
    memory.append(response)
    # erase and rewrite answer
    return response

def run_llm(user_prompt : str, model : str, system_prompt : str = None):
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    
    messages.append({"role": "user", "content": user_prompt})
    
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.025,
        max_tokens=16000,        
    )

    return response.choices[0].message.content

def JSON_llm(user_prompt : str, system_prompt : str = None):
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})

    messages.append({"role": "user", "content": user_prompt})
    
    extract = client.chat.completions.create(
        messages=messages,
        model="lgai/exaone-deep-32b",
        max_tokens=16000, 
    )
    # Extract the last markdown JSON code block
    content = extract.choices[0].message.content
    matches = re.findall(r"```json\s*(\{.*?\})\s*```", content, flags=re.DOTALL)
    if matches:
        content = matches[-1]
    return content

def respond(
    message,
    history: list[dict],
    system_message,
    max_tokens,
    temperature,
    top_p,
):
    # yield loop_workflow(message, EVALUATOR_PROMPT, GENERATOR_PROMPT)
    # use history to improve the response
    response = client.chat.completions.create(
            messages= [{
                "role": "system",
                "content": SINGLE_GENERATOR_PROMPT
            }, *history,{
                "role": "user",
                "content": message
            }],
            model="lgai/exaone-deep-32b",
            max_tokens=24000,
            stream=True
        )

    ans = ""
    history.append({"role": "assistant", "content": ""})
    for chunk in response:
        ans+=chunk.choices[0].delta.content
        history[-1]["content"] = ans
        yield ans

demo = gr.ChatInterface(
    respond,
    title="Nimible Researcher V2",
    type="messages",
    examples=[
        "How does quantum computing work?",
        "Explain the concept of blockchain technology and its applications.",
        "What are the health benefits of a Mediterranean diet?"
    ],
    editable=True,
    run_examples_on_click=True,
    description="For nimble yet deep research on any topic, use Nimible Researcher.",
    flagging_mode="manual",
    flagging_options=["Like", "Dislike"],
    flagging_dir="flagged",
    analytics_enabled=True,
    autofocus=True,
    show_progress="full",
    save_history=True,
    fill_width=True
)

if __name__ == "__main__":
    demo.queue(status_update_rate="auto", default_concurrency_limit=60, max_size=30).launch(share=True)
